name: llm_dart

packages:
  - packages/**

ignore:
  - repo-ref/**

scripts:
  format:
    run: dart format .
    description: Format Dart files in the workspace.
  test:
    run: dart test -j 1
    description: Run repository tests (root package).
  metadata:check:
    run: dart run tool/run_metadata_tests.dart
    description: Run focused providerMetadata/alias tests.
  deps:
    run: dart run tool/check_monorepo_deps.dart
    description: Verify monorepo dependency direction rules.
  exports:
    run: dart run tool/check_public_exports.dart
    description: Verify public export boundary rules.
  surface:
    run: dart run tool/check_provider_surface.dart
    description: Verify Tier 2 provider surface boundary rules.
  fixtures:check:
    run: dart run tool/sync_vercel_fixtures.dart --check
    description: Verify Vercel AI SDK fixtures are synced (repo-ref/ai -> test/fixtures).
  fixtures:sync:
    run: dart run tool/sync_vercel_fixtures.dart --write
    description: Sync Vercel AI SDK fixtures into test/fixtures (never deletes).
  version:set-all:
    run: dart run tool/bump_version.dart set-all
    description: Set all package versions and internal dependency constraints (pass -- --version X.Y.Z).
  version:set:
    run: dart run tool/bump_version.dart set
    description: Set a single package version (pass -- --package name --version X.Y.Z).
