name: llm_dart

packages:
  - packages/*
  - examples

scripts:
  bootstrap:
    run: dart run melos bootstrap
    description: Bootstrap all packages (generates local pubspec_overrides.yaml for path linking).
  analyze:
    run: dart run melos exec --fail-fast -- dart analyze --fatal-infos .
    description: Run static analysis for all packages.
  test:
    run: dart run melos exec --fail-fast --dir-exists=test -- dart test
    description: Run tests for all packages.
