import '../../../../models/audio_models.dart';

/// Static OpenAI audio capability catalogs that do not belong inside the
/// request/response orchestration facade.
final class OpenAIAudioCatalog {
  static const String defaultTtsModel = 'tts-1';
  static const String defaultSttModel = 'whisper-1';
  static const String defaultVoice = 'alloy';
  static const String defaultAudioFormat = 'mp3';

  static const List<VoiceInfo> voices = [
    VoiceInfo(id: 'alloy', name: 'Alloy', description: 'Neutral voice'),
    VoiceInfo(id: 'ash', name: 'Ash', description: 'Expressive voice'),
    VoiceInfo(id: 'ballad', name: 'Ballad', description: 'Melodic voice'),
    VoiceInfo(id: 'coral', name: 'Coral', description: 'Warm voice'),
    VoiceInfo(id: 'echo', name: 'Echo', description: 'Male voice'),
    VoiceInfo(id: 'fable', name: 'Fable', description: 'British accent'),
    VoiceInfo(id: 'nova', name: 'Nova', description: 'Female voice'),
    VoiceInfo(id: 'onyx', name: 'Onyx', description: 'Deep male voice'),
    VoiceInfo(id: 'sage', name: 'Sage', description: 'Wise voice'),
    VoiceInfo(
      id: 'shimmer',
      name: 'Shimmer',
      description: 'Soft female voice',
    ),
    VoiceInfo(id: 'verse', name: 'Verse', description: 'Poetic voice'),
  ];

  static const List<String> _supportedTtsFormats = [
    'mp3',
    'opus',
    'aac',
    'flac',
    'wav',
    'pcm',
  ];

  static const List<String> supportedSttFormats = [
    'flac',
    'm4a',
    'mp3',
    'mp4',
    'mpeg',
    'mpga',
    'oga',
    'ogg',
    'wav',
    'webm',
  ];

  static List<String> supportedTtsFormats() {
    return _supportedTtsFormats;
  }

  static const List<LanguageInfo> supportedLanguages = [
    LanguageInfo(code: 'en', name: 'English'),
    LanguageInfo(code: 'zh', name: 'Chinese'),
    LanguageInfo(code: 'de', name: 'German'),
    LanguageInfo(code: 'es', name: 'Spanish'),
    LanguageInfo(code: 'ru', name: 'Russian'),
    LanguageInfo(code: 'ko', name: 'Korean'),
    LanguageInfo(code: 'fr', name: 'French'),
    LanguageInfo(code: 'ja', name: 'Japanese'),
    LanguageInfo(code: 'pt', name: 'Portuguese'),
    LanguageInfo(code: 'tr', name: 'Turkish'),
    LanguageInfo(code: 'pl', name: 'Polish'),
    LanguageInfo(code: 'ca', name: 'Catalan'),
    LanguageInfo(code: 'nl', name: 'Dutch'),
    LanguageInfo(code: 'ar', name: 'Arabic'),
    LanguageInfo(code: 'sv', name: 'Swedish'),
    LanguageInfo(code: 'it', name: 'Italian'),
    LanguageInfo(code: 'id', name: 'Indonesian'),
    LanguageInfo(code: 'hi', name: 'Hindi'),
    LanguageInfo(code: 'fi', name: 'Finnish'),
    LanguageInfo(code: 'vi', name: 'Vietnamese'),
    LanguageInfo(code: 'he', name: 'Hebrew'),
    LanguageInfo(code: 'uk', name: 'Ukrainian'),
    LanguageInfo(code: 'el', name: 'Greek'),
    LanguageInfo(code: 'ms', name: 'Malay'),
    LanguageInfo(code: 'cs', name: 'Czech'),
    LanguageInfo(code: 'ro', name: 'Romanian'),
    LanguageInfo(code: 'da', name: 'Danish'),
    LanguageInfo(code: 'hu', name: 'Hungarian'),
    LanguageInfo(code: 'ta', name: 'Tamil'),
    LanguageInfo(code: 'no', name: 'Norwegian'),
    LanguageInfo(code: 'th', name: 'Thai'),
    LanguageInfo(code: 'ur', name: 'Urdu'),
    LanguageInfo(code: 'hr', name: 'Croatian'),
    LanguageInfo(code: 'bg', name: 'Bulgarian'),
    LanguageInfo(code: 'lt', name: 'Lithuanian'),
    LanguageInfo(code: 'la', name: 'Latin'),
    LanguageInfo(code: 'mi', name: 'Maori'),
    LanguageInfo(code: 'ml', name: 'Malayalam'),
    LanguageInfo(code: 'cy', name: 'Welsh'),
    LanguageInfo(code: 'sk', name: 'Slovak'),
    LanguageInfo(code: 'te', name: 'Telugu'),
    LanguageInfo(code: 'fa', name: 'Persian'),
    LanguageInfo(code: 'lv', name: 'Latvian'),
    LanguageInfo(code: 'bn', name: 'Bengali'),
    LanguageInfo(code: 'sr', name: 'Serbian'),
    LanguageInfo(code: 'az', name: 'Azerbaijani'),
    LanguageInfo(code: 'sl', name: 'Slovenian'),
    LanguageInfo(code: 'kn', name: 'Kannada'),
    LanguageInfo(code: 'et', name: 'Estonian'),
    LanguageInfo(code: 'mk', name: 'Macedonian'),
    LanguageInfo(code: 'br', name: 'Breton'),
    LanguageInfo(code: 'eu', name: 'Basque'),
    LanguageInfo(code: 'is', name: 'Icelandic'),
    LanguageInfo(code: 'hy', name: 'Armenian'),
    LanguageInfo(code: 'ne', name: 'Nepali'),
    LanguageInfo(code: 'mn', name: 'Mongolian'),
    LanguageInfo(code: 'bs', name: 'Bosnian'),
    LanguageInfo(code: 'kk', name: 'Kazakh'),
    LanguageInfo(code: 'sq', name: 'Albanian'),
    LanguageInfo(code: 'sw', name: 'Swahili'),
    LanguageInfo(code: 'gl', name: 'Galician'),
    LanguageInfo(code: 'mr', name: 'Marathi'),
    LanguageInfo(code: 'pa', name: 'Punjabi'),
    LanguageInfo(code: 'si', name: 'Sinhala'),
    LanguageInfo(code: 'km', name: 'Khmer'),
    LanguageInfo(code: 'sn', name: 'Shona'),
    LanguageInfo(code: 'yo', name: 'Yoruba'),
    LanguageInfo(code: 'so', name: 'Somali'),
    LanguageInfo(code: 'af', name: 'Afrikaans'),
    LanguageInfo(code: 'oc', name: 'Occitan'),
    LanguageInfo(code: 'ka', name: 'Georgian'),
    LanguageInfo(code: 'be', name: 'Belarusian'),
    LanguageInfo(code: 'tg', name: 'Tajik'),
    LanguageInfo(code: 'sd', name: 'Sindhi'),
    LanguageInfo(code: 'gu', name: 'Gujarati'),
    LanguageInfo(code: 'am', name: 'Amharic'),
    LanguageInfo(code: 'yi', name: 'Yiddish'),
    LanguageInfo(code: 'lo', name: 'Lao'),
    LanguageInfo(code: 'uz', name: 'Uzbek'),
    LanguageInfo(code: 'fo', name: 'Faroese'),
    LanguageInfo(code: 'ht', name: 'Haitian Creole'),
    LanguageInfo(code: 'ps', name: 'Pashto'),
    LanguageInfo(code: 'tk', name: 'Turkmen'),
    LanguageInfo(code: 'nn', name: 'Nynorsk'),
    LanguageInfo(code: 'mt', name: 'Maltese'),
    LanguageInfo(code: 'sa', name: 'Sanskrit'),
    LanguageInfo(code: 'lb', name: 'Luxembourgish'),
    LanguageInfo(code: 'my', name: 'Myanmar'),
    LanguageInfo(code: 'bo', name: 'Tibetan'),
    LanguageInfo(code: 'tl', name: 'Tagalog'),
    LanguageInfo(code: 'mg', name: 'Malagasy'),
    LanguageInfo(code: 'as', name: 'Assamese'),
    LanguageInfo(code: 'tt', name: 'Tatar'),
    LanguageInfo(code: 'haw', name: 'Hawaiian'),
    LanguageInfo(code: 'ln', name: 'Lingala'),
    LanguageInfo(code: 'ha', name: 'Hausa'),
    LanguageInfo(code: 'ba', name: 'Bashkir'),
    LanguageInfo(code: 'jw', name: 'Javanese'),
    LanguageInfo(code: 'su', name: 'Sundanese'),
  ];

  const OpenAIAudioCatalog._();
}
