name: llm_dart_ollama
description: Ollama provider implementations for llm_dart.
version: 0.11.0-alpha.1
license: MIT
homepage: https://github.com/Latias94/llm_dart
repository: https://github.com/Latias94/llm_dart
issue_tracker: https://github.com/Latias94/llm_dart/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  llm_dart_provider: ^0.11.0-alpha.1
  llm_dart_provider_utils: ^0.11.0-alpha.1
  llm_dart_transport: ^0.11.0-alpha.1

dev_dependencies:
  llm_dart_ai: ^0.11.0-alpha.1
  lints: ^6.0.0
  llm_dart_test:
    path: ../llm_dart_test
  test: ^1.27.0
