import 'package:llm_dart_core/llm_dart_core.dart';

/// Thrown when a result object is accessed but no output was generated.
///
/// This mirrors Vercel AI SDK's `NoOutputGeneratedError`.
class NoOutputGeneratedError extends LLMError {
  const NoOutputGeneratedError({String message = 'No output generated.'})
      : super(message);

  @override
  String toString() => 'No output generated: $message';
}

/// Thrown when no object could be generated or validated.
///
/// This mirrors Vercel AI SDK's `NoObjectGeneratedError` concept.
class NoObjectGeneratedError extends LLMError {
  /// The raw text that was generated by the model (best-effort).
  final String? text;

  /// Best-effort finish reason, when available.
  final LLMFinishReason? finishReason;

  /// Best-effort usage snapshot, when available.
  final UsageInfo? usage;

  /// Best-effort response metadata, when available.
  final LLMResponseMetadataPart? responseMetadata;

  /// Original cause for debugging (optional).
  final Object? cause;

  const NoObjectGeneratedError({
    String message = 'No object generated.',
    this.text,
    this.finishReason,
    this.usage,
    this.responseMetadata,
    this.cause,
  }) : super(message);

  @override
  String toString() =>
      'No object generated: $message${cause == null ? '' : ' (cause: $cause)'}';
}

/// Thrown when no images were returned by an image generation call.
///
/// Mirrors Vercel AI SDK's `NoImageGeneratedError`.
class NoImageGeneratedError extends LLMError {
  /// Provider response snapshot for debugging (optional).
  final ImageGenerationResponse? response;

  /// Provider response metadata snapshots (best-effort; optional).
  final List<ImageModelResponseMetadata>? responses;

  const NoImageGeneratedError({
    String message = 'No image generated.',
    this.response,
    this.responses,
  }) : super(message);

  @override
  String toString() => 'No image generated: $message';
}

/// Thrown when no speech audio was returned by a text-to-speech call.
///
/// Mirrors Vercel AI SDK's `NoSpeechGeneratedError`.
class NoSpeechGeneratedError extends LLMError {
  /// Provider response snapshot for debugging (optional).
  final TTSResponse? response;

  /// Provider response metadata snapshots (best-effort; optional).
  final List<SpeechModelResponseMetadata>? responses;

  const NoSpeechGeneratedError({
    String message = 'No speech generated.',
    this.response,
    this.responses,
  }) : super(message);

  @override
  String toString() => 'No speech generated: $message';
}

/// Thrown when no transcript text was returned by a transcription call.
///
/// Mirrors Vercel AI SDK's `NoTranscriptGeneratedError`.
class NoTranscriptGeneratedError extends LLMError {
  /// Provider response snapshot for debugging (optional).
  final STTResponse? response;

  /// Provider response metadata snapshots (best-effort; optional).
  final List<TranscriptionModelResponseMetadata>? responses;

  const NoTranscriptGeneratedError({
    String message = 'No transcript generated.',
    this.response,
    this.responses,
  }) : super(message);

  @override
  String toString() => 'No transcript generated: $message';
}

/// Thrown when no videos were returned by an experimental video generation call.
///
/// Mirrors Vercel AI SDK's `NoVideoGeneratedError`.
class NoVideoGeneratedError extends LLMError {
  /// Provider response snapshot for debugging (optional).
  final ExperimentalVideoGenerationResponse? response;

  const NoVideoGeneratedError({
    String message = 'No video generated.',
    this.response,
  }) : super(message);

  @override
  String toString() => 'No video generated: $message';
}

/// Thrown when the model tries to call a tool that is not available.
///
/// Mirrors Vercel AI SDK's `NoSuchToolError`.
class NoSuchToolError extends LLMError {
  final String toolName;
  final List<String>? availableTools;

  NoSuchToolError({
    required this.toolName,
    this.availableTools,
    String? message,
  }) : super(message ?? _defaultNoSuchToolMessage(toolName, availableTools));

  static String _defaultNoSuchToolMessage(
    String toolName,
    List<String>? availableTools,
  ) {
    final suffix = availableTools == null
        ? 'No tools are available.'
        : 'Available tools: ${availableTools.join(', ')}.';
    return "Model tried to call unavailable tool '$toolName'. $suffix";
  }

  @override
  String toString() => "No such tool: $message";
}

/// Thrown when a tool call's input is invalid (e.g. invalid JSON or schema mismatch).
///
/// Mirrors Vercel AI SDK's `InvalidToolInputError`.
class InvalidToolInputError extends LLMError {
  final String toolName;
  final String? toolCallId;
  final String? input;
  final List<String>? validationErrors;

  InvalidToolInputError({
    required this.toolName,
    this.toolCallId,
    this.input,
    this.validationErrors,
    String message = 'Invalid tool input.',
  }) : super(message);

  @override
  String toString() {
    final parts = <String>['Invalid tool input ($toolName): $message'];
    final callId = toolCallId;
    if (callId != null && callId.isNotEmpty) {
      parts.add('toolCallId=$callId');
    }
    final errors = validationErrors;
    if (errors != null && errors.isNotEmpty) {
      parts.add('errors=${errors.join('; ')}');
    }
    return parts.join(' ');
  }
}

/// Thrown when a tool call repair hook fails.
///
/// Mirrors Vercel AI SDK's `ToolCallRepairError`.
class ToolCallRepairError extends LLMError {
  final Object originalError;
  final Object cause;

  ToolCallRepairError({
    required this.originalError,
    required this.cause,
    String? message,
  }) : super(message ?? 'Error repairing tool call: $cause');

  @override
  String toString() => 'Tool call repair error: $message';
}

/// Thrown when encoding/decoding UI message stream chunks fails.
///
/// Mirrors Vercel AI SDK's `UIMessageStreamError`.
class UiMessageStreamError extends LLMError {
  final Object cause;
  final String? chunkType;
  final String? chunkId;

  UiMessageStreamError({
    required this.cause,
    this.chunkType,
    this.chunkId,
    String message = 'UI message stream error.',
  }) : super(message);

  @override
  String toString() {
    final type = chunkType;
    final id = chunkId;
    final extra = <String>[
      if (type != null && type.isNotEmpty) 'chunkType=$type',
      if (id != null && id.isNotEmpty) 'chunkId=$id',
    ];
    return 'UI message stream error: $message'
        '${extra.isEmpty ? '' : ' (${extra.join(', ')})'} (cause: $cause)';
  }
}

/// Thrown when an API surface is called with invalid arguments.
///
/// Mirrors Vercel AI SDK's `InvalidArgumentError`.
class InvalidArgumentError extends LLMError {
  final String argument;
  final Object? value;

  const InvalidArgumentError({
    required this.argument,
    this.value,
    String message = 'Invalid argument.',
  }) : super(message);

  @override
  String toString() =>
      'Invalid argument ($argument): $message${value == null ? '' : ' (value: $value)'}';
}

/// @deprecated Use [MissingToolResultsError] instead.
class MissingToolResultError extends LLMError {
  final String toolCallId;
  final String? toolName;

  @Deprecated('Use MissingToolResultsError(toolCallIds: ...) instead.')
  MissingToolResultError({
    required this.toolCallId,
    this.toolName,
    String? message,
  }) : super(message ?? 'Missing tool result for tool call "$toolCallId".');

  @override
  String toString() => 'Missing tool result: $message';
}

/// Thrown when one or more tool-call ids have no corresponding tool-result.
///
/// Mirrors Vercel AI SDK's `MissingToolResultsError`.
class MissingToolResultsError extends LLMError {
  final List<String> toolCallIds;

  MissingToolResultsError({
    required List<String> toolCallIds,
    String? message,
  })  : toolCallIds = List<String>.unmodifiable(toolCallIds),
        super(
          message ??
              'Tool result${toolCallIds.length > 1 ? 's are' : ' is'} missing for tool call${toolCallIds.length > 1 ? 's' : ''} '
                  '${toolCallIds.join(', ')}.',
        );

  @override
  String toString() => 'Missing tool results: $message';
}

/// Thrown when an unsupported model protocol/version is encountered.
///
/// Mirrors Vercel AI SDK's `UnsupportedModelVersionError`.
class UnsupportedModelVersionError extends LLMError {
  final String version;
  final List<String>? supportedVersions;

  const UnsupportedModelVersionError({
    required this.version,
    this.supportedVersions,
    String message = 'Unsupported model version.',
  }) : super(message);

  @override
  String toString() => 'Unsupported model version: $message '
      '(version=$version${supportedVersions == null ? '' : ', supported=${supportedVersions!.join(', ')}'})';
}

/// Thrown when a tool approval response references an unknown approval id.
///
/// Mirrors Vercel AI SDK's `InvalidToolApprovalError`.
class InvalidToolApprovalError extends LLMError {
  final String approvalId;

  InvalidToolApprovalError({
    required this.approvalId,
    String? message,
  }) : super(
          message ??
              'Tool approval response references unknown approvalId: "$approvalId". '
                  'No matching tool-approval-request found in message history.',
        );

  @override
  String toString() => 'Invalid tool approval response: $message';
}

/// Thrown when a tool call id referenced by an approval request cannot be found.
///
/// Mirrors Vercel AI SDK's `ToolCallNotFoundForApprovalError`.
class ToolCallNotFoundForApprovalError extends LLMError {
  final String toolCallId;
  final String approvalId;

  ToolCallNotFoundForApprovalError({
    required this.toolCallId,
    required this.approvalId,
    String? message,
  }) : super(
          message ??
              'Tool call "$toolCallId" not found for approval request "$approvalId".',
        );

  @override
  String toString() => 'Tool call not found for approval request: $message';
}
